workspace:
  base: /go
  path: src/github.com/emersonmatsumoto/go-hello-world

pipeline:
  build:
    image: golang:1.8
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - sleep 10
      - cd todo
      - go get -v
      - go test -v -cover


